using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Cryptography;
using System.Threading;
using Cysharp.Threading.Tasks;
using MemoryPack;

namespace ASCL.Persistence {
    public sealed class MemoryPackSaveStore<T> where T : class {
        private readonly string _directory; private readonly string _gameVersion; private readonly int _schemaVersion; private readonly Dictionary<int,ISaveMigration<T>> _migrations=new(); private readonly IDevelopmentMirrorWriter<T>? _mirrorWriter;
        public MemoryPackSaveStore(string directory,string gameVersion,int schemaVersion,IEnumerable<ISaveMigration<T>>? migrations=null,IDevelopmentMirrorWriter<T>? mirrorWriter=null){if(string.IsNullOrWhiteSpace(directory))throw new ArgumentException("Save directory is required.",nameof(directory));if(string.IsNullOrWhiteSpace(gameVersion))throw new ArgumentException("Game version is required.",nameof(gameVersion));if(schemaVersion<1)throw new ArgumentOutOfRangeException(nameof(schemaVersion));_directory=Path.GetFullPath(directory);_gameVersion=gameVersion;_schemaVersion=schemaVersion;_mirrorWriter=mirrorWriter;if(migrations!=null)foreach(ISaveMigration<T> migration in migrations){if(migration.FromVersion<1||migration.FromVersion>=schemaVersion)throw new ArgumentOutOfRangeException(nameof(migrations));if(!_migrations.TryAdd(migration.FromVersion,migration))throw new InvalidOperationException($"Duplicate migration from version {migration.FromVersion}.");}}

        public async UniTask SaveAsync(string slot,T value,CancellationToken cancellationToken=default){if(value==null)throw new ArgumentNullException(nameof(value));string normalized=NormalizeSlot(slot);Directory.CreateDirectory(_directory);byte[] payload=MemoryPackSerializer.Serialize(value);var container=new SaveContainer{SchemaVersion=_schemaVersion,GameVersion=_gameVersion,SavedAtUtcTicks=DateTime.UtcNow.Ticks,Slot=normalized,Payload=payload,PayloadSha256=ComputeHash(payload)};byte[] bytes=MemoryPackSerializer.Serialize(container);string path=PathFor(normalized,".sav");string temp=path+".tmp";string backup=path+".bak";await WriteDurableAsync(temp,bytes,cancellationToken);ReplaceWithBackup(temp,path,backup);if(_mirrorWriter!=null)await _mirrorWriter.WriteAsync(PathFor(normalized,".json"),container,value,cancellationToken);}

        public async UniTask<SaveLoadResult<T>> LoadAsync(string slot,CancellationToken cancellationToken=default){string normalized=NormalizeSlot(slot);string primary=PathFor(normalized,".sav");string backup=primary+".bak";SaveLoadResult<T> result=await TryLoadAsync(primary,normalized,cancellationToken);if(result.Succeeded||result.Status==SaveLoadStatus.FutureVersion)return result;if(File.Exists(backup)){SaveLoadResult<T> recovered=await TryLoadAsync(backup,normalized,cancellationToken);if(recovered.Succeeded)return new SaveLoadResult<T>(SaveLoadStatus.RecoveredFromBackup,recovered.Value,result.Error);}return result;}

        public UniTask DeleteAsync(string slot,CancellationToken cancellationToken=default){string normalized=NormalizeSlot(slot);cancellationToken.ThrowIfCancellationRequested();foreach(string suffix in new[]{".sav",".sav.bak",".sav.tmp",".json"}){string path=PathFor(normalized,suffix);if(File.Exists(path))File.Delete(path);}return UniTask.CompletedTask;}

        public UniTask<IReadOnlyList<SaveSlotInfo>> ListSlotsAsync(CancellationToken cancellationToken=default){var result=new List<SaveSlotInfo>();if(Directory.Exists(_directory))foreach(string path in Directory.EnumerateFiles(_directory,"*.sav",SearchOption.TopDirectoryOnly)){cancellationToken.ThrowIfCancellationRequested();var info=new FileInfo(path);result.Add(new SaveSlotInfo(Path.GetFileNameWithoutExtension(path),info.Length,info.LastWriteTimeUtc));}result.Sort(static(a,b)=>b.LastWriteUtc.CompareTo(a.LastWriteUtc));return UniTask.FromResult<IReadOnlyList<SaveSlotInfo>>(result);}

        private async UniTask<SaveLoadResult<T>> TryLoadAsync(string path,string slot,CancellationToken ct){if(!File.Exists(path))return new SaveLoadResult<T>(SaveLoadStatus.NotFound,null,"Save file was not found.");try{byte[] bytes=await File.ReadAllBytesAsync(path,ct);SaveContainer? c=MemoryPackSerializer.Deserialize<SaveContainer>(bytes);if(c==null||c.Slot!=slot||!CryptographicOperations.FixedTimeEquals(c.PayloadSha256,ComputeHash(c.Payload)))return new SaveLoadResult<T>(SaveLoadStatus.Corrupt,null,"Header or checksum validation failed.");if(c.SchemaVersion>_schemaVersion)return new SaveLoadResult<T>(SaveLoadStatus.FutureVersion,null,$"Save version {c.SchemaVersion} is newer than supported version {_schemaVersion}.");T? value=MemoryPackSerializer.Deserialize<T>(c.Payload);if(value==null)return new SaveLoadResult<T>(SaveLoadStatus.Corrupt,null,"Payload was empty.");int version=c.SchemaVersion;while(version<_schemaVersion){if(!_migrations.TryGetValue(version,out ISaveMigration<T>? migration))return new SaveLoadResult<T>(SaveLoadStatus.Corrupt,null,$"Missing migration from version {version}.");value=migration.Migrate(value)??throw new InvalidOperationException("Migration returned null.");version++;}if(version!=c.SchemaVersion)await SaveAsync(slot,value,ct);return new SaveLoadResult<T>(SaveLoadStatus.Success,value,null);}catch(OperationCanceledException){throw;}catch(Exception ex){return new SaveLoadResult<T>(SaveLoadStatus.Corrupt,null,ex.Message);}}

        private static async UniTask WriteDurableAsync(string path,byte[] bytes,CancellationToken ct){using(var stream=new FileStream(path,FileMode.Create,FileAccess.Write,FileShare.None,4096,FileOptions.Asynchronous|FileOptions.WriteThrough)){await stream.WriteAsync(bytes,0,bytes.Length,ct);await stream.FlushAsync(ct);}}
        private static void ReplaceWithBackup(string temp,string target,string backup){if(!File.Exists(target)){File.Move(temp,target);return;}if(File.Exists(backup))File.Delete(backup);try{File.Replace(temp,target,backup);}catch(Exception ex)when(ex is PlatformNotSupportedException or IOException or UnauthorizedAccessException){File.Move(target,backup);try{File.Move(temp,target);}catch{if(!File.Exists(target)&&File.Exists(backup))File.Move(backup,target);throw;}}}
        private static byte[] ComputeHash(byte[] bytes){using SHA256 sha=SHA256.Create();return sha.ComputeHash(bytes);}
        private string PathFor(string slot,string suffix)=>Path.Combine(_directory,slot+suffix);
        private static string NormalizeSlot(string slot){if(string.IsNullOrWhiteSpace(slot))throw new ArgumentException("Slot is required.",nameof(slot));string value=slot.Trim();if(value.IndexOfAny(Path.GetInvalidFileNameChars())>=0||value.Contains("..",StringComparison.Ordinal))throw new ArgumentException("Slot contains invalid characters.",nameof(slot));return value;}
    }
}
