using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ASCL.SourceGen {
    [Generator]
    public sealed class EntitySystemGenerator:IIncrementalGenerator {
        private const string AttributeName="ASCL.Entities.EntitySystemAttribute";
        public void Initialize(IncrementalGeneratorInitializationContext context){var systems=context.SyntaxProvider.ForAttributeWithMetadataName(AttributeName,static(n,_)=>n is ClassDeclarationSyntax,static(c,_)=>(INamedTypeSymbol)c.TargetSymbol).Collect();context.RegisterSourceOutput(context.CompilationProvider.Combine(systems),static(spc,p)=>Emit(spc,p.Left,p.Right));}
        private static void Emit(SourceProductionContext context,Compilation compilation,ImmutableArray<INamedTypeSymbol> systems){if(systems.IsDefaultOrEmpty)return;string assembly=Sanitize(compilation.AssemblyName??"Assembly");var unique=new Dictionary<string,INamedTypeSymbol>(StringComparer.Ordinal);foreach(INamedTypeSymbol system in systems)unique[system.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)]=system;var source=new StringBuilder();source.AppendLine("// <auto-generated/>");source.AppendLine("namespace ASCL.Generated {");source.Append("public static class ").Append(assembly).AppendLine("EntitySystems {");source.AppendLine("public static void Register(global::ASCL.Entities.EntitySystemRegistry registry) {");foreach(INamedTypeSymbol system in unique.Values.OrderBy(static s=>s.ToDisplayString(),StringComparer.Ordinal)){if(system.IsAbstract)continue;if(!HasParameterlessConstructor(system)){context.ReportDiagnostic(Diagnostic.Create(new DiagnosticDescriptor("ASCL001","Entity system needs a parameterless constructor","Entity system '{0}' must have an accessible parameterless constructor","ASCL",DiagnosticSeverity.Error,true),system.Locations.FirstOrDefault(),system.Name));continue;}source.Append("registry.Register(new ").Append(system.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).AppendLine("());");}source.AppendLine("}");if(compilation.GetTypeByMetadataName("UnityEngine.RuntimeInitializeOnLoadMethodAttribute")!=null){source.AppendLine("[global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]");source.Append("private static void AutoRegister()=>global::ASCL.Entities.EntityModuleCatalog.Register(\"").Append(Escape(compilation.AssemblyName??assembly)).Append("\",Register);").AppendLine();}source.AppendLine("}}");context.AddSource(assembly+"EntitySystems.g.cs",source.ToString());}
        private static bool HasParameterlessConstructor(INamedTypeSymbol type)=>type.InstanceConstructors.Any(static c=>c.Parameters.Length==0&&c.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal);
        private static string Sanitize(string value){var b=new StringBuilder(value.Length);foreach(char c in value)b.Append(char.IsLetterOrDigit(c)?c:'_');if(b.Length==0||char.IsDigit(b[0]))b.Insert(0,'_');return b.ToString();}
        private static string Escape(string value)=>value.Replace("\\","\\\\").Replace("\"","\\\"");
    }
}
